### ISSUE TITLE
Authentication/Authorization Error When Attempting to add a Photos Account

### ISSUE THREAD

**Issue by creedda** [ente-io/cli#7]
Hello!

Trying to get my account added and running into 401 errors. Wondering if there are limitations that prevent me from being able to use this feature. This is what I get when I run the account add command from within my container:

```
/ # ./ente-cli account add
Enter app type (default: photos):
Use default app type: photos
Enter export directory: /data
Enter email address: ***email on account***
Enter password: ***copy paste password***
Please wait authenticating...
2023/10/25 16:28:38 failed to verify status 401 with err:
Enter password:
```

Is there a character limit to the length of the password? (mine is over 60 characters) Special Characters?

I also have 2-factor enabled on my account, could that be an issue?

Maybe the feature is not available yet for us users as it's too new? :)

I can reach out via email or discord if you would like more private details.

As mentioned, I am using a docker container to run this if you think it might be relevant.

Thank you for looking at my issue. I am very excited about this feature.

**Comment by ua741** [comment]
Hey @creedda,
Can you please write to us on support@ente.io or ping us on Discord.

**Comment by creedda** [comment]
We resolved my issue with adding my account.

You need to ensure that **OTP**, TOTP, and password are all correct and enabled **via the mobile app**.

I did not have OTP enabled via the mobile app.

Running my first sync manually now, we'll see how it goes!
